Implement Tokens, Pools, Deposit and Withdraw
solid-world/solid-world-poc-rewards-sushi pull request #1
Opened 2022-06-03 15:12 UTC by freitasgouvea

This first version of sushiswap rewards POC includes the following features:

- List SCT tokens
- Create new SCT tokens
- List sushiswap pools
- Create new sushiswap pools with new rewarder smart contract
- Pool info page with mint SCT tokens to the rewarder smart contract and update pool rewards
- Pool actions page with mint SCT tokens to account, deposit and withdraw SCT tokens from a pool

2022-06-05 19:12 UTC, jeffprestes requested changes

2022-06-05 19:12 UTC, jeffprestes commented on public/index.html
> +    <title>React App</title>
We know it just for testing purposes but it would be cool if you could customize the manifest, public and other items of create-react-app template to Solid World brand.

2022-06-06 11:17 UTC, freitasgouvea commented on public/index.html
> +    <title>React App</title>
Perfect, i updated index and favicon with new description and our brand

2022-06-06 11:35 UTC, jeffprestes approved these changes

2022-06-06 11:35 UTC, merged